apiVersion: apps/v1
kind: Deployment
metadata:
  name: calenderapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: calenderapp
  template:
    metadata:
      labels:
        app: calenderapp
    spec:
      containers:
      - name: calenderapp
        image: mahmoudibrahem125/calenderapp:latest
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: calenderapp
spec:
  selector:
    app: calenderapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31112
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
status:
  loadBalancer: {}


